plugins {
    id 'com.android.application'
}

android {
    namespace = 'littlewhitebear.signverification'
    compileSdk = 37
    buildToolsVersion = '37.0.0'
    ndkVersion = '30.0.14904198'
    defaultConfig {
        applicationId = "littlewhitebear.signverification"
        minSdk = 28
        targetSdk = 37
        versionCode = 1
        versionName = "1.0"
        externalNativeBuild {
            cmake {
                abiFilters "arm64-v8a"
            }
        }
        ndk {
            abiFilters "arm64-v8a"
        }
    }

    signingConfigs {
        release {
            storeFile = file("key/release.jks")
            storePassword = "123456"
            keyAlias = "key0"
            keyPassword = "123456"
            enableV1Signing = false
            enableV2Signing = true
            enableV3Signing = true            
        }
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.release
            minifyEnabled = true
            shrinkResources = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/jni/CMakeLists.txt")
            version = "4.1.2"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig = true
    }
}

dependencies {
    implementation(fileTree(dir: 'libs', include: ['*.jar']))
}
